/// <reference lib="DOM.Iterable" />

import "./polyfill";

import type {
    AppLoadContext,
    ServerBuild,
    UNSAFE_MiddlewareEnabled as MiddlewareEnabled,
    RouterContextProvider,
} from "react-router";
import { createRequestHandler as createRemixRequestHandler } from "react-router";

type MaybePromise<T> = T | Promise<T>;

/**
 * A function that returns the value to use as `context` in route `loader` and
 * `action` functions.
 *
 * You can think of this as an escape hatch that allows you to pass
 * environment/platform-specific values through to your loader/action, such as
 * values that are generated by Elysia plugins, derive, or beforeHandle hooks.
 */
export type GetLoadContextFunction = (
    context: ElysiaLikeContext,
) => MiddlewareEnabled extends true
    ? MaybePromise<RouterContextProvider>
    : MaybePromise<AppLoadContext>;

/**
 * Minimal interface describing the Elysia context object available in route
 * handlers. This avoids a hard dependency on Elysia's type system while
 * providing access to the request, server info, and derived store values.
 *
 * If you need full Elysia type safety, cast the context:
 * ```ts
 * import type { Context } from "elysia";
 * ```
 */
export interface ElysiaLikeContext {
    request: Request;
    server?: {
        hostname: string;
        port: number;
        /** @deprecated Use development instead */
        development?: boolean;
    };
    store: Record<string, unknown>;
    [key: string]: unknown;
}

/**
 * A function that handles an incoming Elysia request and returns
 * a React Router response. Designed to be passed directly to
 * Elysia's `.all()` method:
 *
 * ```ts
 * app.all("/*", createRequestHandler({ build }));
 * ```
 */
export type ElysiaRequestHandler = (
    context: ElysiaLikeContext,
) => Promise<Response>;

/**
 * Returns a request handler for Elysia that serves the response using
 * React Router.
 *
 * @example
 * ```typescript
 * import { Elysia } from "elysia";
 * import { createRequestHandler } from "react-router-elysia";
 *
 * // When running in development with vite, you can pass a lazy build:
 * // const build = () => import("./build/server/index.js");
 *
 * // Or when running in production, pass the build directly:
 * import * as build from "./build/server/index.js";
 *
 * const app = new Elysia()
 *   .all("/*", createRequestHandler({ build }))
 *   .listen(3000);
 * ```
 */
export function createRequestHandler({
    build,
    getLoadContext,
    mode = process.env.NODE_ENV,
}: {
    build: ServerBuild | (() => Promise<ServerBuild>);
    getLoadContext?: GetLoadContextFunction;
    mode?: string;
}): ElysiaRequestHandler {
    const handleRequest = createRemixRequestHandler(build, mode);

    return async (context) => {
        const request = createRemixRequest(context.request);
        const loadContext = await getLoadContext?.(context);

        return handleRequest(request, loadContext);
    };
}

/**
 * Creates a Web `Request` compatible with React Router from an Elysia request.
 *
 * Since Elysia and Bun already provide standard Web `Request` objects with
 * native Web Streams support, this function performs minimal conversion
 * compared to the Express adapter. Specifically:
 *
 * - **Headers**: Already `Headers` — no conversion needed
 * - **Body**: Already `ReadableStream` — no Node stream conversion needed
 * - **Abort signal**: Available via `request.signal` — no manual `AbortController`
 * - **URL**: Properly formed by Bun from the incoming HTTP request
 *
 * This function does handle two important things:
 *
 * 1. **Proxy header resolution**: Automatically respects `X-Forwarded-Host` and
 *    `X-Forwarded-Proto` headers (common when running behind a reverse proxy like
 *    Caddy, Nginx, or Cloudflare), ensuring React Router generates correct URLs.
 * 2. **Request cloning**: Creates a new `Request` so the body `ReadableStream`
 *    can be consumed by React Router (Bun's original request body can only be
 *    consumed once).
 *
 * You can override the automatic proxy detection by passing explicit `hostname`
 * or `protocol` options.
 */
export function createRemixRequest(
    request: Request,
    options?: {
        /**
         * Override the hostname (e.g., when behind a reverse proxy that doesn't
         * set X-Forwarded-Host).
         */
        hostname?: string;
        /**
         * Override the protocol (e.g., "https" when behind a reverse proxy that
         * doesn't set X-Forwarded-Proto).
         */
        protocol?: string;
    },
): Request {
    const url = new URL(request.url);

    // Respect proxy headers — mirrors the Express adapter's behavior with
    // "trust proxy" enabled, but without needing explicit configuration since
    // Elysia typically runs behind a reverse proxy in production.
    const forwardedHost = request.headers.get("x-forwarded-host");
    const forwardedProto = request.headers.get("x-forwarded-proto");

    // Protocol: explicit override > X-Forwarded-Proto > existing URL protocol
    const protocol =
        options?.protocol ?? forwardedProto ?? url.protocol.replace(":", "");
    url.protocol = protocol + ":";

    // Host: explicit override > X-Forwarded-Host > existing URL host
    const host = options?.hostname ?? forwardedHost;
    if (host) {
        const [hostname, portStr] = host.split(":");
        url.hostname = hostname;
        if (portStr && Number.isSafeInteger(Number(portStr))) {
            url.port = portStr;
        }
    }

    const init: RequestInit = {
        method: request.method,
        headers: request.headers,
        signal: request.signal,
    };

    // Attach body for non-GET/HEAD requests and enable duplex streaming so
    // the body can be read while the request is still being sent. This is
    // required by the Fetch API spec for streaming request bodies.
    if (request.method !== "GET" && request.method !== "HEAD") {
        init.body = request.body;
        (init as { duplex: "half" }).duplex = "half";
    }

    return new Request(url.href, init);
}

/**
 * Returns the headers object unchanged.
 *
 * Unlike the Express adapter which must convert Express's plain-object
 * headers (where values can be `string | string[] | undefined`) into a
 * Web `Headers` instance, Elysia already provides standard Web `Headers`.
 *
 * This function is exported for API parity with `@react-router/express`
 * and can serve as an extension point if custom header transformation is
 * needed.
 */
export function createRemixHeaders(headers: Headers): Headers {
    return new Headers(headers);
}
